<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-QUD8HLU" name="com.training.functional.tests.AdminCreateTrainingSession" tests="8" failures="1" timestamp="28 Jan 2019 10:29:12 GMT" time="87.466" errors="0">
  <testcase name="validLoginTest" time="3.206" classname="com.training.functional.tests.AdminCreateTrainingSession"/>
  <testcase name="AdministrationHomePageValidation" time="5.017" classname="com.training.functional.tests.AdminCreateTrainingSession"/>
  <testcase name="AdministrationHomePageUnderCoursesessions" time="5.487" classname="com.training.functional.tests.AdminCreateTrainingSession"/>
  <testcase name="AddaTrainingSessionPage" time="2.544" classname="com.training.functional.tests.AdminCreateTrainingSession"/>
  <testcase name="AddacoursePage" time="7.330" classname="com.training.functional.tests.AdminCreateTrainingSession"/>
  <testcase name="StudentSubscribe" time="0.062" classname="com.training.functional.tests.AdminCreateTrainingSession"/>
  <testcase name="StudentSessionSubscribe" time="0.207" classname="com.training.functional.tests.AdminCreateTrainingSession">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.training.functional.tests.AdminCreateTrainingSession.StudentSessionSubscribe(AdminCreateTrainingSession.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- StudentSessionSubscribe -->
  <testcase name="StudentSessionSubscribemessage" time="63.613" classname="com.training.functional.tests.AdminCreateTrainingSession"/>
</testsuite> <!-- com.training.functional.tests.AdminCreateTrainingSession -->
